// Auto-generated by scripts/download-token-icons.ts.
// Maps lowercase token addresses to the file extension of the static icon
// committed under `public/token-icons/{address}.{ext}`. Do not edit by hand.

export const LOCAL_TOKEN_ICONS: Record<string, string> = {
  '0x00471c596755c5eb197a3e43683534b4858c2c0f': 'png',
  '0x1ae3498f1b417fe31be544b04b711f27ba437bd3': 'webp',
  '0x249820c0479d0a7fee6a2a3a14583267550f3caf': 'webp',
  '0x26064dd7821f351202c61f0deb97678eef265e36': 'webp',
  '0x2cfc85d8e48f8eab294be644d9e25c3030863003': 'webp',
  '0x6fb9df9530e302be9dc126363bd7529b807f7167': 'webp',
  '0xab09a728e53d3d6bc438be95eed46da0bbe7fb38': 'webp',
  '0xb7b9bc8e8c301e761af20143a3477e5d1890e1dd': 'webp',
  '0xcd1e32b86953d79a6ac58e813d2ea7a1790cab63': 'webp',
  '0xe4d62e62013eaf065fa3f0316384f88559c80889': 'webp',
  '0xf919250541a98a36eadef0e2f03fe0a9ca707fe3': 'webp',
};

export function getLocalTokenIconPath(address: string): string | null {
  const ext = LOCAL_TOKEN_ICONS[address.toLowerCase()];
  return ext ? `/token-icons/${address.toLowerCase()}.${ext}` : null;
}
